apiVersion: apps/v1
kind: Deployment
metadata:
  name: estoque-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estoque
  template:
    metadata:
      labels:
        app: estoque
    spec:
      containers:
      - name: estoque
        image: your-docker-image
        ports:
        - containerPort: 8000
